# Generated by Django 2.1.1 on 2018-10-01 00:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
                ('course_number', models.CharField(max_length=7, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('name', 'course_number'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_section', models.CharField(blank=True, max_length=3, null=True)),
                ('current_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress_core.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profile',
                'ordering': ('user',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('submitted_by', models.CharField(max_length=256, null=True)),
                ('signature', models.CharField(max_length=256, null=True)),
                ('assessment_uri', models.CharField(max_length=256, null=True)),
                ('grade', models.IntegerField(null=True)),
                ('cheated', models.NullBooleanField(default=False)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user progress',
                'verbose_name_plural': 'user progress',
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
            bases=(django_lifecycle.LifecycleModelMixin, models.Model),
        ),
    ]
