# Generated by Django 2.1.1 on 2018-09-25 19:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('assessment_uri', models.CharField(max_length=256, null=True)),
                ('grade', models.IntegerField(null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progress',
                'verbose_name_plural': 'progress',
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
    ]
