# Generated by Django 2.1.1 on 2018-10-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
