# Generated by Django 2.1.1 on 2018-09-29 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress_core', '0002_auto_20180925_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
                ('course_number', models.CharField(max_length=7, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('name', 'course_number'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_section', models.CharField(blank=True, max_length=3, null=True)),
                ('api_key', models.CharField(blank=True, max_length=32, null=True)),
                ('current_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress_core.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profile',
                'ordering': ('user',),
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'get_latest_by': 'created', 'ordering': ('created',), 'verbose_name': 'user progress', 'verbose_name_plural': 'user progress'},
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
