# Generated by Django 2.1.2 on 2018-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0002_auto_20181001_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_section',
            field=models.CharField(blank=True, choices=[('SECTION_010', '010'), ('SECTION_020', '020'), ('SECTION_030', '030'), ('SECTION_040', '040')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='grade',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
