# Generated by Django 2.1.1 on 2018-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0003_auto_20180929_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_section',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='submitted_by',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
