# Generated by Django 2.1.2 on 2018-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0003_auto_20181008_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='grade',
            field=models.FloatField(null=True),
        ),
    ]
