# Generated by Django 2.1.1 on 2018-09-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0004_auto_20180929_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
    ]
