# Generated by Django 2.1.2 on 2018-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0004_auto_20181009_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='grade',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
