# Generated by Django 2.1.2 on 2018-10-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0005_auto_20181009_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='progress_core.Course'),
        ),
    ]
