# Generated by Django 2.1.1 on 2018-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0005_remove_userprofile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='cheater',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
