# Generated by Django 2.1.2 on 2018-10-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0006_auto_20181015_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='excuse_lateness',
            field=models.NullBooleanField(default=False),
        ),
    ]
