# Generated by Django 2.1.1 on 2018-09-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0007_auto_20180929_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='signature',
            field=models.CharField(default='asdf', max_length=256),
            preserve_default=False,
        ),
    ]
