# Generated by Django 2.1.2 on 2018-10-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0007_userprogress_excuse_lateness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='excuse_lateness',
            field=models.CharField(blank=True, choices=[('LATENESS_ABSENCE', 'Absence'), ('LATENESS_SICK', 'Sick'), ('LATENESS_PERSONAL', 'Personal'), ('LATENESS_EXCEPTION', 'Exception')], max_length=50, null=True),
        ),
    ]
