# Generated by Django 2.1.1 on 2018-09-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0008_userprogress_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='cheater',
            new_name='cheated',
        ),
    ]
