# Generated by Django 2.1.1 on 2018-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0010_auto_20180930_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='cheated',
            field=models.NullBooleanField(default=False),
        ),
    ]
