# Generated by Django 2.1.1 on 2018-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0011_auto_20180930_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_section',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
