# Generated by Django 2.1.2 on 2019-01-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0011_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
