# Generated by Django 2.1.2 on 2019-01-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0012_course_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('order',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='progress_core.Term'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='progress_core.Course'),
        ),
    ]
