# Generated by Django 2.1.2 on 2019-04-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0015_auto_20190105_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('-end_date',), 'verbose_name': 'term', 'verbose_name_plural': 'terms'},
        ),
    ]
