# Generated by Django 3.0.7 on 2022-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_core', '0017_auto_20200520_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_section',
            field=models.CharField(blank=True, choices=[('010', '010'), ('020', '020'), ('030', '030'), ('040', '040'), ('050', '050'), ('GD.010', 'GD.010'), ('GD.020', 'GD.020'), ('GD.030', 'GD.030'), ('GD.040', 'GD.040'), ('GD.050', 'GD.050'), ('DF.010', 'DF.010'), ('DF.020', 'DF.020'), ('DF.030', 'DF.030')], max_length=6, null=True),
        ),
    ]
